(() => {
  const SUPABASE_URL='https://awoefnctmalhtywrxizi.supabase.co';
  const SUPABASE_KEY='sb_publishable_1njtXPhuEmASkStTOTDJ1w_lHROXljp';
  const $=s=>document.querySelector(s);
  const frame=$('#previewFrame'),input=$('#previewIdInput'),loadBtn=$('#loadPreviewBtn'),selectBtn=$('#selectBtn'),undoBtn=$('#undoBtn'),redoBtn=$('#redoBtn');
  const fieldsWrap=$('#editorFields'),nothingSelected=$('#nothingSelected'),patchLog=$('#patchLog'),toast=$('#toast'),stageStatus=$('#stageStatus'),brokenCount=$('#brokenCount'),consoleCount=$('#consoleCount'),layerInfo=$('#layerInfo');
  const codeOutput=$('#codeOutput'),jsonOutput=$('#jsonOutput'),copyCodeBtn=$('#copyCodeBtn'),assetList=$('#assetList');
  const controls={text:$('#textValue'),color:$('#colorValue'),background:$('#backgroundValue'),fontSize:$('#fontSizeValue'),opacity:$('#opacityValue'),radius:$('#radiusValue'),display:$('#displayValue'),moveX:$('#moveX'),moveY:$('#moveY'),scale:$('#scaleValue'),rotate:$('#rotateValue'),blur:$('#blurValue'),src:$('#srcValue')};
  let selecting=true,selectedId=null,timer=0,loadToken=0,liveTimer=0,suppressLive=false,currentRow=null;
  const patchEntries=[],sessionPatches=new Map(),uploaded=[];
  const palette=['#ffffff','#e9e2ff','#9b83ff','#53d7ff','#38e6b2','#ff7fa7','#d4b36b','#000000'];

  function notify(msg,type='success'){clearTimeout(timer);toast.textContent=msg;toast.className=`show ${type}`;timer=setTimeout(()=>toast.className='',2300)}
  function send(type,payload={}){frame.contentWindow?.postMessage({source:'4n1f-parent',type,...payload},'*')}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]||m))}
  function currentValues(){return Object.fromEntries(Object.entries(controls).map(([k,el])=>[k,el?.value??'']))}
  function refreshPatchLog(){if(!patchEntries.length){patchLog.innerHTML='<div class="empty">Belum ada patch.</div>';return}patchLog.innerHTML=patchEntries.slice().reverse().map((p,i)=>`<div class="patch-item"><b>${escapeHtml(p.selector||'element')}</b><span>${escapeHtml(p.kind||'Patch')} ${patchEntries.length-i}</span></div>`).join('')}
  function patchSet(){return {format:'4N1F-PATCHSET-V1.2.1',count:sessionPatches.size,patches:[...sessionPatches.values()].map(x=>x.patch)}}
  function renderSessionOutputs(){const items=[...sessionPatches.values()];if(!items.length){codeOutput.textContent='Apply Draft untuk menghasilkan kode.';jsonOutput.textContent='—';copyCodeBtn.disabled=true;return}codeOutput.textContent=items.map(x=>x.code).filter(Boolean).join('\n\n/* ───────────────────────── */\n\n');jsonOutput.textContent=JSON.stringify(patchSet(),null,2);copyCodeBtn.disabled=false}
  function upsertPatch(payload){if(!payload?.patch?.target)return;sessionPatches.set(payload.patch.target,{patch:payload.patch,code:payload.code||'',updated_at:new Date().toISOString()});patchEntries.push({selector:payload.patch.target,kind:'Apply',at:new Date().toISOString()});refreshPatchLog();renderSessionOutputs()}

  async function fetchPreview(id){const controller=new AbortController(),t=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/get_lab_preview_source`,{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`},body:JSON.stringify({input_preview_id:id})});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.message||data?.hint||`RPC gagal (${r.status})`);const row=Array.isArray(data)?data[0]:data;if(!row?.success)throw new Error(row?.message||'Preview tidak ditemukan.');return row}catch(e){if(e?.name==='AbortError')throw new Error('Load preview timeout. Coba lagi.');throw e}finally{clearTimeout(t)}}

  const bridgeSource=String.raw`(() => {
    const css='.__4n1f_selected{outline:2px solid #7dffb2!important;outline-offset:3px!important;cursor:move!important}.__4n1f_hover{outline:1px dashed rgba(125,255,178,.65)!important;outline-offset:2px!important;cursor:pointer!important}#__4n1f_box{position:fixed;z-index:2147483646;border:1px solid #7dffb2;pointer-events:none;display:none}.__4n1f_handle{position:absolute;width:12px;height:12px;border-radius:50%;background:#fff;border:2px solid #111;box-shadow:0 0 0 1px #7dffb2;pointer-events:auto}.__4n1f_handle[data-h="nw"]{left:-7px;top:-7px;cursor:nwse-resize}.__4n1f_handle[data-h="ne"]{right:-7px;top:-7px;cursor:nesw-resize}.__4n1f_handle[data-h="sw"]{left:-7px;bottom:-7px;cursor:nesw-resize}.__4n1f_handle[data-h="se"]{right:-7px;bottom:-7px;cursor:nwse-resize}.__4n1f_rotate_line{position:absolute;left:50%;top:-30px;width:1px;height:28px;background:#7dffb2}.__4n1f_handle[data-h="rotate"]{left:50%;top:-39px;transform:translateX(-50%);cursor:grab;background:#7dffb2}';
    const style=document.createElement('style');style.id='__4n1f_editor_style';style.textContent=css;document.head.appendChild(style);
    const box=document.createElement('div');box.id='__4n1f_box';box.innerHTML='<i class="__4n1f_rotate_line"></i><i class="__4n1f_handle" data-h="nw"></i><i class="__4n1f_handle" data-h="ne"></i><i class="__4n1f_handle" data-h="sw"></i><i class="__4n1f_handle" data-h="se"></i><i class="__4n1f_handle" data-h="rotate"></i>';document.documentElement.appendChild(box);
    let selecting=true,selected=null,hover=null,seq=0,undo=[],redo=[],pending=null,gesture=null,dragMoved=false;
    const ids=new WeakMap();
    const idFor=el=>{if(!ids.has(el))ids.set(el,'e_'+(++seq));return ids.get(el)};
    const selectorFor=el=>{if(el.id)return '#'+CSS.escape(el.id);const parts=[];let n=el;while(n&&n.nodeType===1&&n.tagName.toLowerCase()!=='body'&&parts.length<4){let p=n.tagName.toLowerCase();const cls=[...n.classList].filter(c=>!c.startsWith('__4n1f_')).slice(0,2);if(cls.length)p+='.'+cls.map(CSS.escape).join('.');const par=n.parentElement;if(par){const same=[...par.children].filter(x=>x.tagName===n.tagName);if(same.length>1)p+=':nth-of-type('+(same.indexOf(n)+1)+')'}parts.unshift(p);n=par}return parts.join(' > ')};
    const snap=el=>({text:el.childElementCount?null:el.textContent,style:el.getAttribute('style')||'',src:el.getAttribute?.('src')??null,x:el.dataset.editorX||'0',y:el.dataset.editorY||'0',scale:el.dataset.editorScale||'1',rotate:el.dataset.editorRotate||'0',blur:el.dataset.editorBlur||'0'});
    const restore=(el,s)=>{if(s.text!==null&&el.childElementCount===0)el.textContent=s.text;if(s.style)el.setAttribute('style',s.style);else el.removeAttribute('style');if(el.tagName==='IMG'){if(s.src)el.setAttribute('src',s.src);else el.removeAttribute('src')}el.dataset.editorX=s.x;el.dataset.editorY=s.y;el.dataset.editorScale=s.scale;el.dataset.editorRotate=s.rotate||'0';el.dataset.editorBlur=s.blur;updateBox()};
    const values=el=>{const cs=getComputedStyle(el);return {id:idFor(el),tag:el.tagName.toLowerCase(),selector:selectorFor(el),text:['INPUT','TEXTAREA','SELECT','IMG','VIDEO','CANVAS'].includes(el.tagName)||el.childElementCount?'':el.textContent,color:cs.color||'',background:cs.backgroundColor==='rgba(0, 0, 0, 0)'?'transparent':cs.backgroundColor,fontSize:cs.fontSize||'',opacity:cs.opacity||'1',radius:cs.borderRadius||'',display:['block','flex','grid','none'].includes(cs.display)?cs.display:'',moveX:el.dataset.editorX||'0',moveY:el.dataset.editorY||'0',scale:el.dataset.editorScale||'1',rotate:el.dataset.editorRotate||'0',blur:el.dataset.editorBlur||'0',src:el.getAttribute?.('src')||''}};
    const post=(type,payload={})=>parent.postMessage({source:'4n1f-frame',type,...payload},'*');
    const diagnose=()=>post('diagnostics',{broken:[...document.images].filter(i=>i.complete&&i.naturalWidth===0).length,console:0});
    const applyTransform=(el,x,y,scale,rotate)=>{el.dataset.editorX=String(x);el.dataset.editorY=String(y);el.dataset.editorScale=String(scale);el.dataset.editorRotate=String(rotate);el.style.transform='translate('+x+'px,'+y+'px) rotate('+rotate+'deg) scale('+scale+')'};
    const applyValues=(el,v={})=>{if(v.text!==undefined&&el.childElementCount===0&&!['INPUT','TEXTAREA','SELECT','IMG','VIDEO','CANVAS'].includes(el.tagName))el.textContent=v.text;if(v.color!==undefined)el.style.color=v.color||'';if(v.background!==undefined)el.style.background=v.background||'';if(v.fontSize!==undefined)el.style.fontSize=v.fontSize||'';if(v.opacity!==undefined)el.style.opacity=v.opacity||'';if(v.radius!==undefined)el.style.borderRadius=v.radius||'';if(v.display!==undefined)el.style.display=v.display||'';const x=Number(v.moveX||0),y=Number(v.moveY||0),scale=Math.max(.02,Number(v.scale||1)),rotate=Number(v.rotate||0),blur=Number(v.blur||0);applyTransform(el,x,y,scale,rotate);el.dataset.editorBlur=String(blur);el.style.filter=blur?'blur('+blur+'px)':'';if(v.src!==undefined&&'src' in el&&v.src)el.setAttribute('src',v.src);updateBox()};
    function updateBox(){if(!selecting||!selected||!selected.isConnected||getComputedStyle(selected).display==='none'){box.style.display='none';return}const r=selected.getBoundingClientRect();if(!r.width&&!r.height){box.style.display='none';return}box.style.display='block';box.style.left=r.left+'px';box.style.top=r.top+'px';box.style.width=r.width+'px';box.style.height=r.height+'px'}
    const beginPending=()=>{if(selected&&!pending)pending={el:selected,before:snap(selected),selector:selectorFor(selected)}};
    const commitPending=()=>{if(!pending)return;const after=snap(pending.el);undo.push({el:pending.el,before:pending.before,after,selector:pending.selector});redo=[];post('committed',{selector:pending.selector,values:values(pending.el),undo:undo.length,redo:redo.length});pending=null;updateBox()};
    const choose=el=>{if(!el||el===document.body||el===document.documentElement||el.closest?.('#__4n1f_box'))return;commitPending();document.querySelectorAll('.__4n1f_selected').forEach(x=>x.classList.remove('__4n1f_selected'));el.classList.add('__4n1f_selected');selected=el;post('selected',values(el));updateBox()};
    const codeFor=(el,v)=>{const sel=selectorFor(el);const esc=s=>String(s).replace(/\\/g,'\\\\').replace(/'/g,"\\'");const css=[];if(v.color)css.push('  color: '+v.color+';');if(v.background)css.push('  background: '+v.background+';');if(v.fontSize)css.push('  font-size: '+v.fontSize+';');if(v.opacity!=='')css.push('  opacity: '+v.opacity+';');if(v.radius)css.push('  border-radius: '+v.radius+';');if(v.display)css.push('  display: '+v.display+';');const x=Number(v.moveX||0),y=Number(v.moveY||0),scale=Number(v.scale||1),rotate=Number(v.rotate||0),blur=Number(v.blur||0);if(x||y||scale!==1||rotate)css.push('  transform: translate('+x+'px, '+y+'px) rotate('+rotate+'deg) scale('+scale+');');if(blur)css.push('  filter: blur('+blur+'px);');let code=css.length?sel+' {\n'+css.join('\n')+'\n}':'';const js=[];if(v.text!==undefined&&el.childElementCount===0&&!['INPUT','TEXTAREA','SELECT','IMG','VIDEO','CANVAS'].includes(el.tagName))js.push("document.querySelector('"+esc(sel)+"').textContent = '"+esc(v.text)+"';");if(v.src&&'src' in el)js.push("document.querySelector('"+esc(sel)+"').setAttribute('src', '"+esc(v.src)+"');");if(js.length)code+=(code?'\n\n':'')+js.join('\n');return {code:code||'/* Tidak ada perubahan visual yang perlu diekspor. */',patch:{target:sel,element:idFor(el),changes:v}}};

    document.addEventListener('mouseover',e=>{if(!selecting||e.target.closest?.('#__4n1f_box'))return;const el=e.target;if(hover&&hover!==selected)hover.classList.remove('__4n1f_hover');hover=el;if(el!==selected&&el!==document.body&&el!==document.documentElement)el.classList.add('__4n1f_hover')},true);
    document.addEventListener('mouseout',e=>{if(e.target!==selected)e.target.classList?.remove('__4n1f_hover')},true);
    document.addEventListener('click',e=>{if(!selecting||e.target.closest?.('#__4n1f_box'))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation?.();if(!dragMoved)choose(e.target);dragMoved=false},true);
    document.addEventListener('pointerdown',e=>{if(!selecting||!selected||e.button!==0||e.target!==selected)return;e.preventDefault();beginPending();const v=values(selected);gesture={type:'move',sx:e.clientX,sy:e.clientY,x:Number(v.moveX||0),y:Number(v.moveY||0)};dragMoved=false},true);
    box.addEventListener('pointerdown',e=>{const h=e.target.closest('.__4n1f_handle');if(!h||!selected)return;e.preventDefault();e.stopPropagation();beginPending();const r=selected.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,v=values(selected);if(h.dataset.h==='rotate'){gesture={type:'rotate',cx,cy,startAngle:Math.atan2(e.clientY-cy,e.clientX-cx)*180/Math.PI,rotate:Number(v.rotate||0)}}else{gesture={type:'scale',cx,cy,startDist:Math.max(1,Math.hypot(e.clientX-cx,e.clientY-cy)),scale:Number(v.scale||1)}}});
    addEventListener('pointermove',e=>{if(!gesture||!selected)return;e.preventDefault();const v=values(selected);if(gesture.type==='move'){const dx=e.clientX-gesture.sx,dy=e.clientY-gesture.sy;applyTransform(selected,gesture.x+dx,gesture.y+dy,Number(v.scale||1),Number(v.rotate||0));dragMoved=Math.abs(dx)+Math.abs(dy)>2}else if(gesture.type==='scale'){const d=Math.max(1,Math.hypot(e.clientX-gesture.cx,e.clientY-gesture.cy));applyTransform(selected,Number(v.moveX||0),Number(v.moveY||0),Math.max(.02,gesture.scale*(d/gesture.startDist)),Number(v.rotate||0));dragMoved=true}else if(gesture.type==='rotate'){const a=Math.atan2(e.clientY-gesture.cy,e.clientX-gesture.cx)*180/Math.PI;let rot=gesture.rotate+(a-gesture.startAngle);if(e.shiftKey)rot=Math.round(rot/15)*15;applyTransform(selected,Number(v.moveX||0),Number(v.moveY||0),Number(v.scale||1),rot);dragMoved=true}post('live-values',{values:values(selected)});updateBox()},true);
    addEventListener('pointerup',()=>{if(!gesture)return;gesture=null;commitPending();diagnose()},true);
    addEventListener('keydown',e=>{if(!selecting||!selected||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();beginPending();const v=values(selected),n=e.shiftKey?10:1;let x=Number(v.moveX||0),y=Number(v.moveY||0);if(e.key==='ArrowLeft')x-=n;if(e.key==='ArrowRight')x+=n;if(e.key==='ArrowUp')y-=n;if(e.key==='ArrowDown')y+=n;applyTransform(selected,x,y,Number(v.scale||1),Number(v.rotate||0));post('live-values',{values:values(selected)});commitPending()},true);
    addEventListener('scroll',updateBox,true);addEventListener('resize',updateBox);
    addEventListener('message',e=>{const m=e.data;if(!m||m.source!=='4n1f-parent')return;if(m.type==='mode'){selecting=!!m.selecting;box.style.display=selecting&&selected?'block':'none';updateBox();post('mode',{selecting})}if(m.type==='live'&&selected){beginPending();applyValues(selected,m.values||{});post('live-values',{values:values(selected)});diagnose()}if(m.type==='commit')commitPending();if(m.type==='apply'&&selected){beginPending();applyValues(selected,m.values||{});commitPending();const out=codeFor(selected,values(selected));post('code',{...out,selector:selectorFor(selected)})}if(m.type==='undo'){commitPending();const it=undo.pop();if(it){restore(it.el,it.before);selected=it.el;redo.push(it);post('history',{values:values(it.el),undo:undo.length,redo:redo.length});diagnose()}}if(m.type==='redo'){commitPending();const it=redo.pop();if(it){restore(it.el,it.after);selected=it.el;undo.push(it);post('history',{values:values(it.el),undo:undo.length,redo:redo.length});diagnose()}}if(m.type==='reset'&&selected){commitPending();const it=[...undo].find(x=>x.el===selected);if(it){restore(selected,it.before);post('history',{values:values(selected),undo:undo.length,redo:redo.length});diagnose()}}});
    setTimeout(diagnose,350);setTimeout(diagnose,1400);post('ready');
  })();`;

  function buildDoc(row){const html=String(row.html_code||''),css=String(row.css_code||''),js=String(row.js_code||'');const userScript=`<script>${js}<\/script>`,bridge=`<script>${bridgeSource}<\/script>`,style=`<style>${css}</style>`;if(/<!doctype/i.test(html)||/<html[\s>]/i.test(html)){let doc=html;doc=/<\/head>/i.test(doc)?doc.replace(/<\/head>/i,style+'</head>'):style+doc;doc=/<\/body>/i.test(doc)?doc.replace(/<\/body>/i,userScript+bridge+'</body>'):doc+userScript+bridge;return doc}return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${style}</head><body>${html}${userScript}${bridge}</body></html>`}
  function rgbToHex(color){if(!color||color==='transparent')return '#000000';if(/^#[0-9a-f]{6}$/i.test(color))return color;const m=color.match(/rgba?\((\d+)[,\s]+(\d+)[,\s]+(\d+)/i);if(!m)return '#ffffff';return '#'+[m[1],m[2],m[3]].map(n=>Math.max(0,Math.min(255,Number(n))).toString(16).padStart(2,'0')).join('')}
  function alphaFromColor(color){const m=String(color||'').match(/rgba\([^,]+,[^,]+,[^,]+,\s*([\d.]+)\)/i);return m?Math.round(Number(m[1])*100):(color==='transparent'?0:100)}
  function hexToRgba(hex,alpha){const h=hex.replace('#',''),n=parseInt(h,16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return alpha>=100?`rgb(${r}, ${g}, ${b})`:`rgba(${r}, ${g}, ${b}, ${(alpha/100).toFixed(2)})`}
  function updateColorUI(name,value){const sw=$(`[data-color-open="${name}"]`),picker=$(`[data-color-picker="${name}"]`),alpha=$(`[data-color-alpha="${name}"]`),label=$(`[data-alpha-label="${name}"]`);if(!sw)return;const hex=rgbToHex(value),a=alphaFromColor(value);sw.style.background=value==='transparent'?'linear-gradient(135deg,#fff 0 45%,#d55 45% 55%,#fff 55%)':value;picker.value=hex;alpha.value=String(a);label.textContent=a+'%'}
  function fill(v){if(!v)return;suppressLive=true;selectedId=v.id||selectedId;$('#selectedTag').textContent=v.tag||'—';$('#selectedSelector').textContent=v.selector||'—';fieldsWrap.hidden=false;nothingSelected.hidden=true;for(const [k,el] of Object.entries(controls))if(el)el.value=v[k]??(k==='scale'?'1':'0');controls.text.value=v.text??'';controls.color.value=v.color??'';controls.background.value=v.background??'';controls.fontSize.value=v.fontSize??'';controls.opacity.value=v.opacity??'1';controls.radius.value=v.radius??'';controls.display.value=v.display??'';controls.src.value=v.src??'';updateColorUI('color',controls.color.value);updateColorUI('background',controls.background.value);layerInfo.innerHTML=`<b>${escapeHtml(v.tag||'element')}</b><br><code>${escapeHtml(v.selector||'')}</code>`;requestAnimationFrame(()=>suppressLive=false)}
  function queueLive(){if(suppressLive||!selectedId)return;send('live',{values:currentValues()});clearTimeout(liveTimer);liveTimer=setTimeout(()=>send('commit'),420)}
  function setupColors(){['color','background'].forEach(name=>{const open=$(`[data-color-open="${name}"]`),pop=$(`[data-color-popover="${name}"]`),picker=$(`[data-color-picker="${name}"]`),alpha=$(`[data-color-alpha="${name}"]`),label=$(`[data-alpha-label="${name}"]`),preset=$(`[data-presets="${name}"]`),field=controls[name];preset.innerHTML=palette.map(c=>`<button type="button" class="preset-swatch" data-preset-color="${c}" style="background:${c}" aria-label="${c}"></button>`).join('');open.addEventListener('click',()=>{document.querySelectorAll('.color-popover').forEach(p=>{if(p!==pop)p.hidden=true});pop.hidden=!pop.hidden;if(!pop.hidden){updateColorUI(name,field.value);requestAnimationFrame(()=>{pop.classList.remove('flip-x');if(pop.getBoundingClientRect().right>innerWidth-12)pop.classList.add('flip-x')})}});const applyPicker=()=>{const a=Number(alpha.value||100);label.textContent=a+'%';field.value=hexToRgba(picker.value,a);updateColorUI(name,field.value);queueLive()};picker.addEventListener('input',applyPicker);alpha.addEventListener('input',applyPicker);preset.addEventListener('click',e=>{const b=e.target.closest('[data-preset-color]');if(!b)return;picker.value=b.dataset.presetColor;alpha.value='100';applyPicker()});field.addEventListener('input',()=>{updateColorUI(name,field.value);queueLive()})});document.addEventListener('click',e=>{if(e.target.closest('.color-field'))return;document.querySelectorAll('.color-popover').forEach(p=>p.hidden=true)})}
  function refreshAssets(){assetList.innerHTML=uploaded.length?uploaded.slice().reverse().map(a=>`<div class="asset-item"><b>${escapeHtml(a.name)}</b><span>${Math.round(a.size/1024)} KB • ${escapeHtml(a.type||'file')}</span></div>`).join(''):'<div class="empty">Belum ada upload draft.</div>'}
  function download(name,text,type='text/plain'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200)}

  addEventListener('message',e=>{if(e.source!==frame.contentWindow)return;const m=e.data;if(!m||m.source!=='4n1f-frame')return;if(m.type==='ready'){stageStatus.textContent=stageStatus.textContent.replace('Rendering','Loaded');send('mode',{selecting});notify('Preview siap diedit real-time.')}if(m.type==='selected'){fill(m)}if(m.type==='diagnostics'){brokenCount.textContent=String(m.broken??0);consoleCount.textContent=String(m.console??0)}if(m.type==='live-values')fill(m.values);if(m.type==='committed'){fill(m.values);undoBtn.disabled=!m.undo;redoBtn.disabled=!m.redo}if(m.type==='history'){fill(m.values);undoBtn.disabled=!m.undo;redoBtn.disabled=!m.redo;notify('History diperbarui.')}if(m.type==='code'){upsertPatch(m);notify(`Patch tersimpan • ${sessionPatches.size} elemen aktif.`)}});

  async function loadPreview(){const id=input.value.trim();if(!id)return notify('Masukkan Preview ID dulu.','error');const token=++loadToken;selectedId=null;fieldsWrap.hidden=true;nothingSelected.hidden=false;patchEntries.length=0;sessionPatches.clear();uploaded.length=0;refreshPatchLog();refreshAssets();renderSessionOutputs();undoBtn.disabled=redoBtn.disabled=true;currentRow=null;loadBtn.disabled=true;loadBtn.textContent='Loading…';stageStatus.textContent='Fetching snapshot…';try{const row=await fetchPreview(id);if(token!==loadToken)return;currentRow=row;stageStatus.textContent='Rendering preview…';frame.onload=()=>{if(token===loadToken)send('mode',{selecting})};frame.srcdoc=buildDoc(row)}catch(err){stageStatus.textContent='Load failed';notify(err.message||'Gagal load preview.','error')}finally{if(token===loadToken){loadBtn.disabled=false;loadBtn.textContent='Load Preview'}}}

  Object.values(controls).forEach(el=>{if(!el||el===controls.color||el===controls.background)return;el.addEventListener('input',queueLive);el.addEventListener('change',queueLive)});setupColors();
  loadBtn.addEventListener('click',loadPreview);input.addEventListener('keydown',e=>{if(e.key==='Enter')loadPreview()});selectBtn.addEventListener('click',()=>{selecting=!selecting;selectBtn.classList.toggle('active',selecting);selectBtn.textContent=selecting?'Select':'Interact';send('mode',{selecting});notify(selecting?'Select mode aktif.':'Interaction mode aktif.')});
  $('#applyBtn').addEventListener('click',()=>{if(!selectedId)return notify('Pilih elemen dulu.','error');clearTimeout(liveTimer);send('apply',{values:currentValues()})});$('#resetElementBtn').addEventListener('click',()=>send('reset'));undoBtn.addEventListener('click',()=>send('undo'));redoBtn.addEventListener('click',()=>send('redo'));
  $('#clearPatchesBtn').addEventListener('click',()=>{patchEntries.length=0;sessionPatches.clear();refreshPatchLog();renderSessionOutputs();notify('Session patch dibersihkan.')});
  copyCodeBtn.addEventListener('click',async()=>{const code=codeOutput.textContent||'';if(!sessionPatches.size)return;try{await navigator.clipboard.writeText(code);notify('Code dicopy.')}catch{const ta=document.createElement('textarea');ta.value=code;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();notify('Code dicopy.')}});
  document.querySelectorAll('[data-width]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-width]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');frame.style.width=btn.dataset.width}));
  $('#uploadAssetBtn')?.addEventListener('click',()=>$('#assetUpload')?.click());$('#assetUpload')?.addEventListener('change',()=>{const f=$('#assetUpload').files?.[0];if(!f)return;if(f.size>8*1024*1024){notify('File maksimal 8 MB.','error');$('#assetUpload').value='';return}const r=new FileReader();r.onload=()=>{const dataUrl=String(r.result||''),sig=[f.name,f.size,f.type,dataUrl.slice(-96)].join('|'),found=uploaded.find(a=>a.signature===sig);if(!found)uploaded.push({signature:sig,name:f.name,type:f.type,size:f.size,dataUrl});refreshAssets();controls.src.value=dataUrl;controls.src.dispatchEvent(new Event('input',{bubbles:true}));notify(found?'Asset yang sama dipakai lagi.':f.name+' dipasang ke draft.');$('#assetUpload').value=''};r.readAsDataURL(f)});
  const menu=$('#exportMenu');$('#exportBtn')?.addEventListener('click',()=>menu.hidden=false);$('#closeExportBtn')?.addEventListener('click',()=>menu.hidden=true);menu?.addEventListener('click',e=>{if(e.target===menu){menu.hidden=true;return}const b=e.target.closest('[data-export]');if(!b)return;menu.hidden=true;const kind=b.dataset.export,patchText=sessionPatches.size?JSON.stringify(patchSet(),null,2):'{}',code=sessionPatches.size?codeOutput.textContent:'/* Belum ada patch aktif. */';if(kind==='patch')return download('4N1F-patch-v1.2.1.json',patchText,'application/json');if(kind==='code')return download('4N1F-generated-code-v1.2.1.txt',code);if(kind==='bundle'){const bundle={format:'4N1F-LABS-BUNDLE-V1.2.1',preview_id:input.value.trim(),created_at:new Date().toISOString(),generated_code:code,patch_set:sessionPatches.size?patchSet():null,assets:uploaded.map(({signature,...a})=>a),source:{html:currentRow?.html_code||'',css:currentRow?.css_code||'',js:currentRow?.js_code||''}};download('4N1F-source-bundle-v1.2.1.json',JSON.stringify(bundle,null,2),'application/json')}});
  refreshAssets();refreshPatchLog();renderSessionOutputs();const preset=new URLSearchParams(location.search).get('preview');if(preset){input.value=preset;setTimeout(loadPreview,80)}
})();